<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlowingCandles.Application\BlowingCandles.Application.csproj" />
    <ProjectReference Include="..\BlowingCandles.Infrastructure\BlowingCandles.Infrastructure.csproj" />
  </ItemGroup>

</Project>
