// <auto-generated />
using System;
using BlowingCandles.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlowingCandles.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlowingCandles.Infrastructure.Persistence.Entities.MarketDataRefreshRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("error_message");

                    b.Property<int>("MissingSymbolCount")
                        .HasColumnType("integer")
                        .HasColumnName("missing_symbol_count");

                    b.Property<int>("PersistedSymbolCount")
                        .HasColumnType("integer")
                        .HasColumnName("persisted_symbol_count");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<DateOnly>("RequestedAsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("requested_as_of_date");

                    b.Property<int>("RequestedSymbolCount")
                        .HasColumnType("integer")
                        .HasColumnName("requested_symbol_count");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAsOfDate", "StartedAtUtc")
                        .HasDatabaseName("ix_market_data_refresh_run_requested_as_of_date_started_at_utc");

                    b.HasIndex("Status", "StartedAtUtc")
                        .HasDatabaseName("ix_market_data_refresh_run_status_started_at_utc");

                    b.ToTable("market_data_refresh_run", null, t =>
                        {
                            t.HasCheckConstraint("ck_market_data_refresh_run_missing_symbol_count_non_negative", "\"missing_symbol_count\" >= 0");

                            t.HasCheckConstraint("ck_market_data_refresh_run_persisted_symbol_count_non_negative", "\"persisted_symbol_count\" >= 0");

                            t.HasCheckConstraint("ck_market_data_refresh_run_requested_symbol_count_non_negative", "\"requested_symbol_count\" >= 0");
                        });
                });

            modelBuilder.Entity("BlowingCandles.Infrastructure.Persistence.Entities.MarketDataSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc");

                    b.Property<int>("CoveredSymbolCount")
                        .HasColumnType("integer")
                        .HasColumnName("covered_symbol_count");

                    b.Property<DateOnly>("FirstQuoteDate")
                        .HasColumnType("date")
                        .HasColumnName("first_quote_date");

                    b.Property<DateTimeOffset>("FreshUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fresh_until_utc");

                    b.Property<int>("FreshnessTtlSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("freshness_ttl_seconds");

                    b.Property<DateOnly>("LastQuoteDate")
                        .HasColumnType("date")
                        .HasColumnName("last_quote_date");

                    b.Property<int>("MissingSymbolCount")
                        .HasColumnType("integer")
                        .HasColumnName("missing_symbol_count");

                    b.Property<int>("QuoteRowCount")
                        .HasColumnType("integer")
                        .HasColumnName("quote_row_count");

                    b.Property<long>("RefreshRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("refresh_run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FreshUntilUtc")
                        .HasDatabaseName("ix_market_data_snapshot_fresh_until_utc");

                    b.HasIndex("RefreshRunId")
                        .IsUnique()
                        .HasDatabaseName("ix_market_data_snapshot_refresh_run_id");

                    b.HasIndex("AsOfDate", "CapturedAtUtc")
                        .HasDatabaseName("ix_market_data_snapshot_as_of_date_captured_at_utc");

                    b.ToTable("market_data_snapshot", null, t =>
                        {
                            t.HasCheckConstraint("ck_market_data_snapshot_covered_symbol_count_non_negative", "\"covered_symbol_count\" >= 0");

                            t.HasCheckConstraint("ck_market_data_snapshot_freshness_ttl_seconds_positive", "\"freshness_ttl_seconds\" > 0");

                            t.HasCheckConstraint("ck_market_data_snapshot_missing_symbol_count_non_negative", "\"missing_symbol_count\" >= 0");

                            t.HasCheckConstraint("ck_market_data_snapshot_quote_row_count_non_negative", "\"quote_row_count\" >= 0");
                        });
                });

            modelBuilder.Entity("BlowingCandles.Infrastructure.Persistence.Entities.MarketDataSnapshotMissingSymbolEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("detail");

                    b.Property<bool>("IsRetryable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_retryable");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reason");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_market_data_snapshot_missing_symbol_snapshot_id_symbol");

                    b.ToTable("market_data_snapshot_missing_symbol", (string)null);
                });

            modelBuilder.Entity("BlowingCandles.Infrastructure.Persistence.Entities.MarketDataSnapshotQuoteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("high");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("low");

                    b.Property<DateTimeOffset>("MarketTimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("market_timestamp_utc");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("open");

                    b.Property<DateOnly>("QuoteDate")
                        .HasColumnType("date")
                        .HasColumnName("quote_date");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("symbol");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "QuoteDate")
                        .HasDatabaseName("ix_market_data_snapshot_quote_symbol_quote_date");

                    b.HasIndex("SnapshotId", "Symbol", "QuoteDate")
                        .IsUnique()
                        .HasDatabaseName("ix_market_data_snapshot_quote_snapshot_id_symbol_quote_date");

                    b.ToTable("market_data_snapshot_quote", null, t =>
                        {
                            t.HasCheckConstraint("ck_market_data_snapshot_quote_volume_non_negative", "\"volume\" >= 0");
                        });
                });

            modelBuilder.Entity("BlowingCandles.Infrastructure.Persistence.Entities.MarketDataSnapshotEntity", b =>
                {
                    b.HasOne("BlowingCandles.Infrastructure.Persistence.Entities.MarketDataRefreshRunEntity", "RefreshRun")
                        .WithOne("Snapshot")
                        .HasForeignKey("BlowingCandles.Infrastructure.Persistence.Entities.MarketDataSnapshotEntity", "RefreshRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RefreshRun");
                });

            modelBuilder.Entity("BlowingCandles.Infrastructure.Persistence.Entities.MarketDataSnapshotMissingSymbolEntity", b =>
                {
                    b.HasOne("BlowingCandles.Infrastructure.Persistence.Entities.MarketDataSnapshotEntity", "Snapshot")
                        .WithMany("MissingSymbols")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("BlowingCandles.Infrastructure.Persistence.Entities.MarketDataSnapshotQuoteEntity", b =>
                {
                    b.HasOne("BlowingCandles.Infrastructure.Persistence.Entities.MarketDataSnapshotEntity", "Snapshot")
                        .WithMany("Quotes")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("BlowingCandles.Infrastructure.Persistence.Entities.MarketDataRefreshRunEntity", b =>
                {
                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("BlowingCandles.Infrastructure.Persistence.Entities.MarketDataSnapshotEntity", b =>
                {
                    b.Navigation("MissingSymbols");

                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
